[functions]
  external_node_modules = ["express", "serverless-http", "method-override", "mongoose", "dotenv", "path", "ejs", "cors"]
  node_bundler = "esbuild"
[[redirects]]
  force = true
  from = "/api/posts/*"
  status = 200
  to = "/.netlify/functions/api-posts/:splat"
[[redirects]]
  force = true
  from = "/api/contacts/*"
  status = 200
  to = "/.netlify/functions/api-contacts/:splat"
