[functions]
  external_node_modules = ["express", "serverless-http", "method-override", "mongoose", "dotenv", "path", "ejs"]
  node_bundler = "esbuild"
[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/api/:splat"
